### ISSUE TITLE
Inner classes not working right

### ISSUE THREAD

**Issue by kno10** [dspinellis/UMLGraph#20]
Inner classes don't seem to properly work for me. I've tried three different syntaxes, and gotten mostly two results: 1. an arrow for the outer class self-referencing itself, and 2. an arrow that is seemingly correct (with $ syntax) but the class isn't recognized, and it links to oracle instead.

Below is not a tested example.

```
/**
 * @has - - - B <--- graph links A to A, not B.
 * @has - - - A.B <-- graph links A to A, not B.
 * @has - - - A$B  <--- graph is okay, but links to java.
 */
public class A {
  public class B {
  }
}
```

P.S. "@opt nodecolor" also isn't working in the doclet.

**Comment by kno10** [comment]
Apparently, the problem arises **if the outer class has generics**.
```
/**
 * @has - - - Test.Child
 */
public class Test<A> {
  public class Child {}
}
```
the inner class then uses the name `Test<A>.Child`, and this gives
![UMLGraph example][1]
and when we remove the Generic, we get the expected
![UMLGraph example][2]
If the child is static, it also works:
![UMLGraph example][3]

[1]: https://g.gravizo.com/svg?/**%20@has%20-%20-%20-%20Test.Child%20*/public%20class%20Test%3CA%3E%20{%20public%20class%20Child%20{}}
[2]: https://g.gravizo.com/svg?/**%20@has%20-%20-%20-%20Test.Child%20*/public%20class%20Test%20{%20public%20class%20Child%20{}}
[3]: https://g.gravizo.com/svg?/**%20@has%20-%20-%20-%20Test.Child%20*/public%20class%20Test%3CA%3E%20{%20public%20static%20class%20Child%20{}}

**Comment by dspinellis** [comment]
Excellent, this is very useful!  It should help us find a fix and test it.

**Comment by kno10** [comment]
The `removeTemplate` function apparently kills the inner class name.
