### ISSUE TITLE
broken link for version 5.7.2 on maven repo

### ISSUE THREAD

**Issue by ahonorat** [dspinellis/UMLGraph#28]
Hi,

Hi, I can see the version [5.7.2 on maven-repository](https://maven-repository.com/artifact/org.umlgraph/umlgraph/5.7.2) website but the download fails. Actually it appears that the directory for version 5.7.2 is missing since there is 404 error on the expected [url](https://oss.sonatype.org/content/repositories/staging/org/umlgraph/umlgraph/5.7.2/).
Thanks anyway, very useful tool :)

PS: your tool to find greek names is quite impressive !

**Comment by dspinellis** [comment]
Thank you for bringing this up and for your kind words.  I do not think I maintain the release on [maven-repository.com](https://maven-repository.com/) site. Maybe somebody else uploaded a broken build. You can always build from the distributed source code.
