### ISSUE TITLE
Build issues on JDK7

### ISSUE THREAD

**Issue by spyhunter99** [dspinellis/UMLGraph#33]
I'm getting a few build issues with JDK7.

cannot find package `package com.sun.javadoc`

I've verified that maven is resolving to the correct `tools.jar` file but something else is still whacky. Anyone else run into this?

It seems to work fine on JDK8 though

**Comment by kno10** [comment]
I am closing this, since Java 8 and 11 are current.
Building with 8 seems to be fine; support for Java 9-11 will require a major rewrite, unfortunately. c.f., #51
