### ISSUE TITLE
[ant] BUILD FAILED build.xml:27: exec returned: 128

### ISSUE THREAD

**Issue by nikoSchoinas** [dspinellis/UMLGraph#55]
I am trying to install the software according to instructions in README.txt file. I am facing an issue when I try to follow this step: 
-To compile the Java doclet from the source code run ant on the build.xml file.

So, basically I run "ant built.xml" command but I am getting the below error:

Buildfile: /UMLGraph-5.7_2.32-SNAPSHOT/build.xml
     [echo] git describe --abbrev=6 => 'version'

BUILD FAILED
/UMLGraph-5.7_2.32-SNAPSHOT/build.xml:50: The following error occurred while executing this line:
/UMLGraph-5.7_2.32-SNAPSHOT/build.xml:27: exec returned: 128

I tried to find out what's "exec returned:128" stands for with no success. However, the line 27 in build.xml file has to do with the version from git. Unfortunately, the link which is inside comments in line 20 of the build.xml file is broken and even though I searched about that issue I couldn't find something useful.

When I run the command "git describe" or "git describe --abbrev=6", I am getting:
fatal: No names found, cannot describe anything. 

With a little research I found a post that says "This is caused because git rev-list --tags --max-count=1 is not returning any tags. The expected behavior is that, the build must not terminate when the repository does not have any tag yet." 

I am not a git expert but I far as I can understand maybe the repository has not any tags and that causes the error. 

- OS is Ubuntu 16.04.6 LTS
- git version 2.7.4
- Apache Ant(TM) version 1.9.6 compiled on July 20 2018
- java version "1.8.0_201"

**Comment by dspinellis** [comment]
Thank you for the very clear description.  Please report whether the fix 75cc871a10656a5b1935873ecc5fed815d783a87, addresses your problem.

**Comment by nikoSchoinas** [comment]
The fix solved the problem. I tested the umlgraph with a file from testdata/java folder and the class diagram was successfully produced. 
I also noticed that when you navigate to the build.xml directory, you just need to run "ant" instead of "ant build.xml". Maybe it's obvious but I didn't know it.
