### ISSUE TITLE
I can't get UMLGraph to work in Java 1.8

### ISSUE THREAD

**Issue by foghorn-hash** [dspinellis/UMLGraph#61]
I can't get UMLGraph to work in Java 1.8.

No right CSS files generated to Javadocs with UML.

**Comment by dspinellis** [comment]
Thank you for the report!  Did it work in your environment with previous Java versions?  Does the problem only affect CSS files?  What other files are generated?

**Comment by foghorn-hash** [comment]
Actually I possible haves error in source code of my Maven 3 project because an another project generates the correctly made Javadocs with UML with Jenkins.
